# Generated by Django 4.2.17 on 2025-02-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_topic_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='subscribed_dots',
            field=models.ManyToManyField(blank=True, related_name='subscribed_editors', to='editor.dot'),
        ),
    ]
