# Generated by Django 4.2.18 on 2025-02-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subdot',
            name='content',
            field=models.TextField(),
        ),
    ]
