# Generated by Django 5.0.1 on 2025-03-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_alter_editor_subscribed_dots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
