# Generated by Django 4.2.18 on 2025-02-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_dot_description_alter_subdot_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='subscribed_dots',
            field=models.ManyToManyField(blank=True, related_name='subscribed_editors', to='editor.dot'),
        ),
    ]
