# Generated by Django 4.2.18 on 2025-02-28 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0004_dot_description_alter_subdot_content'),
        ('learning', '0003_subscriptionplan_freetrialusage_usersubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='option_a',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='option_b',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='option_c',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='option_d',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='selected_answer',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('subdot', 'learner')},
        ),
    ]
